name: Deployment pipeline

on:
  push:
    branches:
      - main
    # pull_request:
    #   branches: [master]
    #   types: [opened, synchronize]
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        working-directory: './redux-anecdotes'
        run: npm install
      - name: lint
        working-directory: './redux-anecdotes'
        run: npm run lint
      - name: build
        working-directory: './redux-anecdotes'
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run server, npm start
          working-directory: './redux-anecdotes'
          wait-on: http://localhost:3001
      - name: heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-redux-anecdotes" #Must be unique in Heroku
          heroku_email: "joel.heusala@gmail.com"
