name: Test

on:
  push:
    branches:
      - master
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install 
        working-directory: './redux-anecdotes'
        run: npm install